### without hypermeter tunning 

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

%matplotlib inline

x,y = make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=15)
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.30,random_state=42)

logistic = LogisticRegression()
logistic.fit(x_train,y_train)

y_pred = logistic.predict(x_test)
score=accuracy_score(y_test,y_pred)
classification_report=classification_report(y_test,y_pred)
confusion_matrix=confusion_matrix(y_test,y_pred)
print(score)
print(classification_report)
print(confusion_matrix)

0.9166666666666666
              precision    recall  f1-score   support

           0       0.91      0.93      0.92       157
           1       0.92      0.90      0.91       143

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

[[146  11]
 [ 14 129]]


### with gridsearchcv

In [29]:
model=LogisticRegression()
penalty=['l1','l2','elasticnet']
c_values=[100,10,1.0,0.1,0.01]
solver=['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']

prams=dict(penalty=penalty,C=c_values,solver=solver)

In [30]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()

grid=GridSearchCV(estimator=model,param_grid=prams,cv=cv,n_jobs=-1,scoring='accuracy')

In [31]:
grid.fit(x_train,y_train)

e:\codes\course\mlenv\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
200 fits failed out of a total of 375.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "e:\codes\course\mlenv\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "e:\codes\course\mlenv\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\codes\course\mlenv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1194, in fit
    solver = _check_solv

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [32]:
grid.best_params_

{'C': 0.01, 'penalty': 'l1', 'solver': 'saga'}

In [33]:
grid.best_score_

np.float64(0.9242857142857142)

In [36]:
y_pred=grid.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(accuracy_score(y_test,y_pred))
print(classification_report(y_pred,y_test))
print(confusion_matrix(y_test,y_pred))


0.92
              precision    recall  f1-score   support

           0       0.95      0.90      0.93       165
           1       0.89      0.94      0.91       135

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

[[149   8]
 [ 16 127]]


### randomizedsearchcv

In [37]:
from sklearn.model_selection import RandomizedSearchCV

model=LogisticRegression()
random=RandomizedSearchCV(estimator=model,param_distributions=prams,cv=cv,n_jobs=-1,scoring='accuracy')


random.fit(x_train,y_train)

e:\codes\course\mlenv\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
15 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "e:\codes\course\mlenv\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "e:\codes\course\mlenv\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\codes\course\mlenv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1194, in fit
    solver = _check_solver

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
                   estimator=LogisticRegression(), n_jobs=-1,
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [38]:
random.best_params_

{'solver': 'saga', 'penalty': 'l1', 'C': 0.01}

In [39]:
random.best_score_

np.float64(0.9242857142857142)

In [40]:
y_pred=random.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(accuracy_score(y_test,y_pred))
print(classification_report(y_pred,y_test))
print(confusion_matrix(y_test,y_pred))

0.92
              precision    recall  f1-score   support

           0       0.95      0.90      0.93       165
           1       0.89      0.94      0.91       135

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

[[149   8]
 [ 16 127]]
