In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

%matplotlib inline

x,y = make_classification(n_samples=1000,n_features=10,n_classes=3,n_informative=3,random_state=15)
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.30,random_state=42)



In [2]:
logistic = LogisticRegression(multi_class='ovr')
logistic.fit(x_train,y_train)

y_pred = logistic.predict(x_test)
score=accuracy_score(y_test,y_pred)
classification_report=classification_report(y_test,y_pred)
confusion_matrix=confusion_matrix(y_test,y_pred)
print(score)
print(classification_report)
print(confusion_matrix)

0.79
              precision    recall  f1-score   support

           0       0.87      0.82      0.84       102
           1       0.81      0.73      0.77       102
           2       0.71      0.82      0.76        96

    accuracy                           0.79       300
   macro avg       0.79      0.79      0.79       300
weighted avg       0.80      0.79      0.79       300

[[84 10  8]
 [ 3 74 25]
 [10  7 79]]


e:\codes\course\mlenv\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
